apiVersion: v1
kind: Service
metadata:
  name: blazorapp-service
spec:
  type: ClusterIP
  selector:
    app: instarent-blazorapp
  ports:
    - protocol: TCP
      name: https
      port: 443
     # targetPort: 443
     # nodePort: 32062 # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    - protocol: TCP
      name: http
      port: 80
     # targetPort: 80
     # nodePort: 30062 # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)      
